### PR TITLE
Add bandit, git-legal, pylint and pep8 plugins, and increase some thresholds

### PR DESCRIPTION
**Pull request by JasperCraeghs**
Add bandit, git-legal, pylint and pep8 plugins, and increase threshold where it makes sense.

### CODE REVIEW

**Comment by Letme** [comment]
Fix linelength of pep8 to 120 (or remove that check). There is also some problems with pylint...

**Comment by Letme** [comment]
Don't overstreatch this PR with fixes. I would say we wrap it, remove the wip and merge. Then solve issues in another mr

**Comment by JasperCraeghs** [comment]
The last commit regarding coverity_services.py should solve why the example didn't build properly last time I built it, but I can't confirm this yet without VPN.

**Comment by Letme** [comment]
I am merging this because it is going out of scope.

**Pull request merged**
