### PR TITLE
Add reference to traceability items in Comment column

### PR DESCRIPTION
**Pull request by JasperCraeghs**
The tool reports a warning when a `traceability_collection` exists in the build environment and the item ID could not be found inside it.

Resolves issue #27.

### CODE REVIEW

**Comment by JasperCraeghs** [comment]
I think the text in the cell doesn't actually get modified yet. I need to look into this further.

**Comment by JasperCraeghs** [comment]
Now hyperlinks should be interactive and item IDs as well (if they are found in the traceability collection of the build environment).

**Comment by Letme** [comment]
Do you want to ad more things or shall we merge this in (WIP)?

**Comment by JasperCraeghs** [comment]
The pdfdoc in 82100 failed.

**Pull request merged**
